import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
   <body>
  <nav className="bg-blue-600 text-white px-8 py-4 flex justify-between">
    <h1 className="font-bold text-lg">HRMS System</h1>
    <div className="space-x-6">
      <Link href="/" className="hover:underline">
        Dashboard
      </Link>
      <Link href="/employees" className="hover:underline">
        Employees
      </Link>
    </div>
  </nav>
  {children}
</body>
    </html>
  );
}
